### ISSUE TITLE
Is "scholarships funded" metric up to date?

### ISSUE THREAD

**Issue by missmatsuko** [cascadiajs/cascadiajs-2019#11]
The scholarships funded number has been "8" for a while now, and the number appears to be hard-coded in the template:
https://github.com/cascadiajs/cascadiajs-2019/blob/9ebb2064879b7d85dc48f85b9d9524823e8edded/src/views/index/index-template.js#L49-L50

Is this supposed to be pulling a number from an API, or maybe it's just periodically updated manually?

**Comment by crtr0** [comment]
Yeah, it's not up to date. Sadly, it's something that I just have to update manually :/
