### ISSUE TITLE
Some pages display `"Cannot read property 'type' of undefined"`

### ISSUE THREAD

**Issue by trivikr** [cascadiajs/cascadiajs-2019#24]
**Describe the bug**
Some pages display `"Cannot read property 'type' of undefined"` sometimes

**To Reproduce**
* Visit any speaker page. For example https://2019.cascadiajs.com/speakers/trivikram-kamat
* Keep reloading it
* Note that page will display `"Cannot read property 'type' of undefined"` in one of the loads.
* When I reloaded the page 18 times, the error was shown thrice

**Expected behavior**
The error is not displayed.

**Screenshots**
![cascadiajs-cannot-read-property](https://user-images.githubusercontent.com/16024985/68334494-98acb480-008f-11ea-8f31-48573fdae99b.png)

**Comment by crtr0** [comment]
Twas a bug. It's fixed now, thanks for reporting :)
